version: "2"

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge

# todo

services:

  backend:
    build: ./backend
    mem_limit: 512m
    volumes:
      - ./backend:/data/www/default
    environment:
      - NGINX_GENERATE_DEFAULT_VHOST=true
    networks:
      - back-tier
    logging:
      options:
        max-size: "1m"
#        max-file: "2"

  database:
    image: wirnex/postgis:1.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zoomtivity
    networks:
      - back-tier
    expose:
      - 3306
    logging:
      driver: "json-file"
    mem_limit: 512m
    restart: always

